### ISSUE TITLE
How to plot GCAM results in bar charts?

### ISSUE THREAD

**Issue by atmos-project** [JGCRI/metis#235]
Hi,

This tool is very useful. I have installed it and I can extract GCAM scenario results using it. I see a lot of plot options though maps but at the moment I would be more interested in plotting GCAM results in bar charts. Is this feature available? 

Thanks.

**Comment by zarrarkhan** [comment]
Hi,

Thanks for the comment. In the future `metis` is going to be used exclusively for `Input-Output` and `interconnectivity` analysis. We will removing the mapping functionality as well as the charting functions. If you want you can take a look at the current charting functions in metis: `metis.chartsProcess.R` and some basic examples in this script here: https://github.com/JGCRI/metis/blob/master/extras/metis.master.R.

For the future please look at the following packages which will remain under active development:

- Mapping (rmap): https://github.com/JGCRI/rmap
- Extract data from GCAM (gcamextractor): https://github.com/JGCRI/gcamextractor
- Interactive Charts & Maps Dashboard (argus): https://github.com/JGCRI/argus

`Argus` is planned to be released in **August 2021** and will be your best tool to look at charts, maps and interact with the data and all of this will be in the online application without the need for any software. You can then download the maps, charts and tables that you would need. Charts in Argus will look something like:

<img width="943" alt="charts" src="https://user-images.githubusercontent.com/7863115/125702815-bc55a947-7d8f-4308-8ba1-2c6139fac0c4.PNG">
